// spell-checker: disable

import Polyglot from 'node-polyglot';

export enum OrderItemCardContentPhrases {
  REMOVE_ORDER = 'remove-order',
  IMAGE_DIMENSIONS = 'image-dimensions',
  WIDTH = 'width',
  HEIGHT = 'height',
  FRAME_NUMBER = 'frame-number',
  PASSEPARTOUT_NUMBER = 'passepartout-number',
  PASSEPARTOUT_WIDTH = 'passepartout-width',
  GLASS_TRANSPARENT = 'glass-transparent',
  GLASS_MATTE = 'glass-matte',
  GLASS_NONE = 'glass-none',
  GLASS_PERSPEX = 'glass-perspex',
  GLASS_MIRROR = 'glass-mirror',
  ADHESIONS = 'adhesions',
  PRINTS = 'prints',
  DESCRIPTION = 'description',
  NOTES = 'notes',
  QUANTITY = 'quantity',
  UNIT_PRICE = 'unit-price',
  PRICE = 'price',
  DIMENSIONS_REQUIRED = 'dimensions-required',
  NOTHING_FOUND = 'nothing-found',
  WIDTH_PLACEHOLDER = 'width-placeholder',
  HEIGHT_PLACEHOLDER = 'height-placeholder',
  FRAME_NUMBER_PLACEHOLDER = 'frame-number-placeholder',
  PASSEPARTOUT_NUMBER_PLACEHOLDER = 'passepartout-number-placeholder',
  PASSEPARTOUT_WIDTH_PLACEHOLDER = 'passepartout-width-placeholder',
  ADHESIONS_PLACEHOLDER = 'adhesions-placeholder',
  PRINTS_PLACEHOLDER = 'prints-placeholder',
  DESCRIPTION_PLACEHOLDER = 'description-placeholder',
  QUANTITY_PLACEHOLDER = 'quantity-placeholder',
  UNIT_PRICE_PLACEHOLDER = 'unit-price-placeholder',
  CREATE_NEW_FRAME = 'create-new-frame',
  CREATE_FRAME = 'create-frame',
  CREATE_NEW_PASSEPARTOUT = 'create-new-passepartout',
  CREATE_PASSEPARTOUT = 'create-passepartout',
  CREATE_NEW_ADHESION = 'create-new-adhesion',
  CREATE_ADHESION = 'create-adhesion',
  CREATE_NEW_PRINT = 'create-new-print',
  CREATE_PRINT = 'create-print',
  CREATE_NEW_DESCRIPTION = 'create-new-description',
  CREATE_DESCRIPTION = 'create-description',
}

export const orderItemCardContent = new Polyglot({
  locale: 'he',
  phrases: {
    [OrderItemCardContentPhrases.REMOVE_ORDER]: 'הסר הזמנה',
    [OrderItemCardContentPhrases.IMAGE_DIMENSIONS]: 'מידות תמונה',
    [OrderItemCardContentPhrases.WIDTH]: 'רוחב',
    [OrderItemCardContentPhrases.HEIGHT]: 'גובה',
    [OrderItemCardContentPhrases.FRAME_NUMBER]: 'מספר מסגרת',
    [OrderItemCardContentPhrases.PASSEPARTOUT_NUMBER]: 'מספר פספרטו',
    [OrderItemCardContentPhrases.PASSEPARTOUT_WIDTH]: 'רוחב פספרטו',
    [OrderItemCardContentPhrases.GLASS_TRANSPARENT]: 'זכוכית שקוף',
    [OrderItemCardContentPhrases.GLASS_MATTE]: 'זכוכית מט',
    [OrderItemCardContentPhrases.GLASS_NONE]: 'בלי זכוכית',
    [OrderItemCardContentPhrases.GLASS_PERSPEX]: 'פרספקס',
    [OrderItemCardContentPhrases.GLASS_MIRROR]: 'מראה',
    [OrderItemCardContentPhrases.ADHESIONS]: 'הדבקות',
    [OrderItemCardContentPhrases.PRINTS]: 'הדפסות',
    [OrderItemCardContentPhrases.DESCRIPTION]: 'תיאור',
    [OrderItemCardContentPhrases.NOTES]: 'הערות',
    [OrderItemCardContentPhrases.QUANTITY]: 'כמות',
    [OrderItemCardContentPhrases.UNIT_PRICE]: 'מחיר יחידה',
    [OrderItemCardContentPhrases.PRICE]: 'מחיר',
    [OrderItemCardContentPhrases.DIMENSIONS_REQUIRED]: 'רוחב וגובה נדרשים',
    [OrderItemCardContentPhrases.NOTHING_FOUND]: 'לא נמצאו תוצאות',
    [OrderItemCardContentPhrases.WIDTH_PLACEHOLDER]: 'הזן רוחב',
    [OrderItemCardContentPhrases.HEIGHT_PLACEHOLDER]: 'הזן גובה',
    [OrderItemCardContentPhrases.FRAME_NUMBER_PLACEHOLDER]: 'בחר מספר מסגרת',
    [OrderItemCardContentPhrases.PASSEPARTOUT_NUMBER_PLACEHOLDER]: 'בחר מספר פספרטו',
    [OrderItemCardContentPhrases.PASSEPARTOUT_WIDTH_PLACEHOLDER]: 'הזן רוחב פספרטו',
    [OrderItemCardContentPhrases.ADHESIONS_PLACEHOLDER]: 'בחר סוג הדבקה',
    [OrderItemCardContentPhrases.PRINTS_PLACEHOLDER]: 'בחר סוג הדפסה',
    [OrderItemCardContentPhrases.DESCRIPTION_PLACEHOLDER]: 'בחר תיאור',
    [OrderItemCardContentPhrases.QUANTITY_PLACEHOLDER]: 'הזן כמות',
    [OrderItemCardContentPhrases.UNIT_PRICE_PLACEHOLDER]: 'הזן מחיר יחידה',
    [OrderItemCardContentPhrases.CREATE_NEW_FRAME]: 'צור מסגרת חדשה',
    [OrderItemCardContentPhrases.CREATE_FRAME]: 'יצירת מסגרת',
    [OrderItemCardContentPhrases.CREATE_NEW_PASSEPARTOUT]: 'צור פספרטו חדש',
    [OrderItemCardContentPhrases.CREATE_PASSEPARTOUT]: 'יצירת פספרטו',
    [OrderItemCardContentPhrases.CREATE_NEW_ADHESION]: 'צור הדבקה חדשה',
    [OrderItemCardContentPhrases.CREATE_ADHESION]: 'יצירת הדבקה',
    [OrderItemCardContentPhrases.CREATE_NEW_PRINT]: 'צור הדפסה חדשה',
    [OrderItemCardContentPhrases.CREATE_PRINT]: 'יצירת הדפסה',
    [OrderItemCardContentPhrases.CREATE_NEW_DESCRIPTION]: 'צור תיאור חדש',
    [OrderItemCardContentPhrases.CREATE_DESCRIPTION]: 'יצירת תיאור',
  },
});
