version: '3.8'
services:
  db:
    container_name: database
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - docker-postgres:/var/lib/postgresql/data

volumes:
  docker-postgres:
