// spell-checker: disable

import Polyglot from 'node-polyglot';

export enum UserFormContentPhrases {
  FIRST_NAME_REQUIRED = 'first-name-required',
  LAST_NAME_REQUIRED = 'last-name-required',
  USERNAME_MIN_LENGTH = 'username-min-length',
  INVALID_EMAIL = 'invalid-email',
  PASSWORD_MIN_LENGTH = 'password-min-length',
  USER_DETAILS = 'user-details',
  FIRST_NAME = 'first-name',
  LAST_NAME = 'last-name',
  USERNAME = 'username',
  EMAIL = 'email',
  PASSWORD = 'password',
  CONFIRM_PASSWORD = 'confirm-password',
  PASSWORD_SECTION = 'password-section',
  ROLE_SECTION = 'role-section',
  ROLE = 'role',
  FORM_DATA_INVALID = 'form-data-invalid',
  ERROR_WHILE_CREATING = 'error-while-creating',
  USER_CREATED = 'user-created',
  ERROR_WHILE_UPDATING = 'error-while-updating',
  USER_UPDATED = 'user-updated',
  ERROR_WHILE_DELETING = 'error-while-deleting',
  USER_DELETED = 'user-deleted',
  EMAIL_REQUIRED = 'email-required',
  EMAIL_ALREADY_EXISTS = 'email-already-exists',
}

export const userFormContent = new Polyglot({
  locale: 'he',
  phrases: {
    [UserFormContentPhrases.FIRST_NAME_REQUIRED]: 'שם פרטי נדרש',
    [UserFormContentPhrases.LAST_NAME_REQUIRED]: 'שם משפחה נדרש',
    [UserFormContentPhrases.USERNAME_MIN_LENGTH]: 'שם המשתמש חייב להיות לפחות 3 תווים',
    [UserFormContentPhrases.INVALID_EMAIL]: 'כתובת אימייל לא חוקית',
    [UserFormContentPhrases.PASSWORD_MIN_LENGTH]: 'הסיסמה חייבת להיות לפחות 8 תווים',
    [UserFormContentPhrases.FIRST_NAME]: 'שם פרטי',
    [UserFormContentPhrases.LAST_NAME]: 'שם משפחה',
    [UserFormContentPhrases.USERNAME]: 'שם משתמש',
    [UserFormContentPhrases.EMAIL]: 'כתובת אימייל',
    [UserFormContentPhrases.PASSWORD]: 'סיסמה',
    [UserFormContentPhrases.CONFIRM_PASSWORD]: 'אימות סיסמה',
    [UserFormContentPhrases.PASSWORD_SECTION]: 'סיסמה',
    [UserFormContentPhrases.ROLE_SECTION]: 'תפקיד',
    [UserFormContentPhrases.ROLE]: 'תפקיד',
    [UserFormContentPhrases.FORM_DATA_INVALID]: 'נתונים שגויים',
    [UserFormContentPhrases.ERROR_WHILE_CREATING]: 'שגיאה ביצירת משתמש',
    [UserFormContentPhrases.USER_CREATED]: 'משתמש נוצר',
    [UserFormContentPhrases.ERROR_WHILE_UPDATING]: 'שגיאה בעדכון משתמש',
    [UserFormContentPhrases.USER_UPDATED]: 'משתמש עודכן',
    [UserFormContentPhrases.ERROR_WHILE_DELETING]: 'שגיאה במחיקת משתמש',
    [UserFormContentPhrases.USER_DELETED]: 'משתמש מחוק',
    [UserFormContentPhrases.EMAIL_REQUIRED]: 'כתובת אימייל נדרשת',
    [UserFormContentPhrases.EMAIL_ALREADY_EXISTS]: 'כתובת אימייל כבר קיימת',
    [UserFormContentPhrases.USER_DETAILS]: 'פרטי משתמש',
  },
});
