// spell-checker: disable

import Polyglot from 'node-polyglot';

export enum StatCardListPhrases {
  CUSTOMERS = 'customers',
  ALL_CUSTOMERS = 'all-customers',
  ORDERS = 'orders',
  ALL_ORDERS = 'all-orders',
  PENDING = 'pending',
  PROCESSING = 'processing',
  SHIPPED = 'shipped',
  DELIVERED = 'delivered',
  ORDER_TRACKING = 'order-tracking',
  PENDING_ORDERS = 'pending-orders',
  PROCESSING_ORDERS = 'processing-orders',
  SHIPPED_ORDERS = 'shipped-orders',
  DELIVERED_ORDERS = 'delivered-orders',
  OVERVIEW = 'overview',
  NEW = 'new',
  IN_PROGRESS = 'in-progress',
  READY = 'ready',
  COMPLETED = 'completed',
  NEW_ORDERS = 'new-orders',
  IN_PROGRESS_ORDERS = 'in-progress-orders',
  READY_ORDERS = 'ready-orders',
  COMPLETED_ORDERS = 'completed-orders',
}

export const statCardListContent = new Polyglot({
  locale: 'he',
  phrases: {
    [StatCardListPhrases.CUSTOMERS]: 'לקוחות',
    [StatCardListPhrases.ALL_CUSTOMERS]: 'כל הלקוחות',
    [StatCardListPhrases.ORDERS]: 'הזמנות',
    [StatCardListPhrases.ALL_ORDERS]: 'כל ההזמנות',
    [StatCardListPhrases.PENDING]: 'ממתין ל',
    [StatCardListPhrases.PROCESSING]: 'מעבד',
    [StatCardListPhrases.SHIPPED]: 'נשלח',
    [StatCardListPhrases.DELIVERED]: 'נמסר',
    [StatCardListPhrases.ORDER_TRACKING]: 'מעקב אחר הזמנות',
    [StatCardListPhrases.PENDING_ORDERS]: 'הזמנות ממתין ל',
    [StatCardListPhrases.PROCESSING_ORDERS]: 'הזמנות מעבד',
    [StatCardListPhrases.SHIPPED_ORDERS]: 'הזמנות נשלח',
    [StatCardListPhrases.DELIVERED_ORDERS]: 'הזמנות נמסר',
    [StatCardListPhrases.OVERVIEW]: 'תמצאות',
    [StatCardListPhrases.NEW]: 'חדש',
    [StatCardListPhrases.IN_PROGRESS]: 'בעבודה',
    [StatCardListPhrases.READY]: 'מוכן',
    [StatCardListPhrases.COMPLETED]: 'הושלם',
    [StatCardListPhrases.NEW_ORDERS]: 'הזמנות חדשות',
    [StatCardListPhrases.IN_PROGRESS_ORDERS]: 'הזמנות בעבודה',
    [StatCardListPhrases.READY_ORDERS]: 'הזמנות מוכנות',
    [StatCardListPhrases.COMPLETED_ORDERS]: 'הזמנות שהושלמו',
  },
});
